facebook/idx

- packages/babel-plugin-idx/package.json
- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
- packages/babel-plugin-idx/yarn.lock
The code comment explains the rationale here:
> We're very strict about the shape of idx. Some transforms, like
> babel-plugin-transform-async-to-generator", will convert arrow
> functions inside async functions into regular functions. So we do
> our transformation before any one else interferes.
> Apply idx transform before other transforms (Fixes #4)

- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
First, check if there's an `idx` binding in scope. If you're using `idx`, you likely have a top-level `var idx = require('idx')` or `import idx from 'idx';`. We can check for this cheaply since the scope has already been calculated. If that fails, then do a quick regex check for `idx` in the source.
> Add fast path for code without "idx" in the source [1/2]

- README.md
- circle.yml
- package.json
- packages/babel-plugin-idx/package.json
- packages/idx/package.json
Unfortunately, due to https://github.com/lerna/lerna/issues/671, I had to add `--concurrency=1` to `lerna bootstrap`.
Note: `"testEnvironment": "node"` makes the tests a bit faster since we avoid jsdom - which isn't necessary for these tests.
> Setup CircleCI testing

- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
This optimization greatly simplifies the transform, and results in smaller output code. For example, `idx(a => a.b.c.d)`:
**Before**
```js
var x, y, z;
(x = base) != null ?
(y = x.b) != null ?
(z = y.c) != null ?
z.d :
z :
y :
x;
// minified (62 bytes)
var x,y,z;null!=(x=base)?null!=(y=x.b)?null!=(z=y.c)?z.d:z:y:x
```
**After**
```js
var z;
(z = base) != null ?
(z = z.b) != null ?
(z = z.c) != null ?
z.d :
z :
z :
z;
// minified (56 bytes)
var z;null!=(z=base)&&null!=(z=z.b)&&null!=(z=z.c)?z.d:z
```
If your minifier is less performant, the gains are higher.
FYI: While working on this, I noticed that the `this` is not correct for method calls. I'll try to fix that later on.
> Reuse temporary variable in transformed code

- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
woops :blush
Without this fix:
```js
(() => idx(base, _ => _.b));
// transforms into:
() => {
var _ref;
return idx(base, _ => _.b);
};
```
> Fix idx transform when idx's parent is a scope creating expression

- README.md
- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
With this PR, instead of searching for calls to the idx function, it searches
for require('idx') or import idx from 'idx' calls, finds all
references to the assigned variable and transform them.
This also allows us to remove the require() call, which is no longer
needed (and in fact is causing issues when using haste in RN due to not
being able to find the idx module (since it no longer has the
@providesModule annotation).
----
This is a follow-up PR based on the feedback received in https://github.com/facebookincubator/idx/pull/22, reusing the commit ed87aaa1eb430e1e735fd6200d43a895300e3cd7 from @zertosh and adding a small extra functionality (the ability to customize the require/import name).
> Rework the idx babel transform to be more reliable

- packages/babel-plugin-idx/src/babel-plugin-idx.js
The idea behind `path.scope.getOwnBinding('idx')` was that since the scope is already pre-calculated, we could avoid the regex check in cases where `idx` was a top-level import. However, if you do `import type idx from 'idx'`, you get these warnings:
```
console.warn ../node_modules/babel-traverse/lib/scope/index.js:1015
You or one of the Babel plugins you are using are using Flow declarations as bindings.
Support for this will be removed in version 6.8. To find out the caller, grep for this
message and change it to a `console.trace()`.
```
Since this is a micro-optimization, I don't think it's worth the confusing warning (especially during tests).
> Remove fast "idx" binding check

- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
After #23, the `idx` import module name and the binding itself don't have to be `idx`. This PR only does the fast path test when `importName` is `idx`. It also fixes the `importName` test so that it doesn't accidentally trip the fast path test (the updated tests would fail without this change).
> Fix fast-path incorrect exit on non-idx import names

- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
Adding the temp var to the scope of an async method, messes up the `this` reference when using `babel-plugin-transform-async-to-generator`. I don't have better solution than to special handle the scoping in cases where the immediate scope is an async method. Setting `_blockHoist: 3` all of the time doesn't seem to affect the tests, but because this option is poorly documented, I'm not sure on what other consequences that may have. So I'd rather play it safe.
Without this fix, the test would actually transform to:
```js
class Foo {
bar() {
return _asyncToGenerator(function* () {
var _ref,
_this = this;
(_ref = base) != null ? _ref.b : _ref;
return _this;
})();
}
}
```
@wbinnssmith hit this issue in Nuclide a while ago, and I just remembered about this.
> Fix idx calls in async methods

- README.md
- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
Big breaking change! `this` in the callback parameter doesn't work (see #20), but rather than fixing that, since flow doesn't support function calls anyway (see #24), lets just remove the support altogether. If flow adds support for function calls, then I'll re-add this and fix the `this` binding.
Also added a bit to the README emphasizing flow so it's clear that there's a connection between this module and flow.
> Throw on call expression in the callback parameter

- packages/idx/src/idx.js
Required for some build configurations.
For example with this it's possible to use idx with Typescript as is with following typing:
```typescript
declare module "idx" {
function idx<T, R>(props: T, getPath: (props: T) => R): R;
export default idx;
}
```
Typescript usage example with strict null checks:
```typescript
import idx from "idx";
interface IState {
foo?: {
bar?: {
baz?: number;
};
};
}
const state: IState = {};
var num = idx(state, _ => _.foo!.bar!.baz); 
```
> Add default ES6 export

- packages/idx/src/idx.js
The simplifications from #35 were great, but it can be taken further. Construct and use the error parsing regexs directly.
> Further simplify idx error message parsing

- packages/idx/src/idx.js
Fixes the only lint warnings in the project.
**Test Plan:**
Ran `npm run lint` and `npm run test` successfully.
> Fix regex lint warning

- packages/idx/src/idx.js
- packages/idx/src/idx.test.js
Made nullPattern, undefinedPattern regexes to be case insensitive. Extended unit tests. Fixes #46
> [Issue 46]: Capital case errors shall be matched by *pattern regexes

- packages/babel-plugin-idx/src/babel-plugin-idx.js
- packages/babel-plugin-idx/src/babel-plugin-idx.test.js
Nested idx calls cause an error in the Babel transform. Having this code:
```javascript
const idx = require('idx');
idx(
idx(
idx(base, _ => _.a.b),
_ => _.c.d
),
_ => _.e.f
);
```
Results in an error:
```
ReferenceError: unknown: Container is falsy
```
I'm adding a commit with the failing tests and then one with the fix.
> Bugfix: transforming nested idx calls

- packages/idx/src/idx.d.ts
- packages/idx/src/idx.test.ts
This will allow TypeScript with strictNullCheck flag on to work with
this package. We're making the `prop` argument in the accessor function
a deeply required object so we can safely access it deeply.
I've also added a test file for TypeScript definition so we can make
sure changes to the definition is not breaking them. Currently tests are
not run with any sort of CI. If adding TypeScript as dependency is
desired we can add thtat to test scripts as well
> Enhance TypeScript types

- package.json
- packages/idx/package.json
- packages/idx/src/idx.d.ts
- packages/idx/src/idx.test.ts
- tsconfig.json
- yarn.lock
This adds support for methods in the deep structure. It makes sure arguments types are carried over up to 7 arguments. 
Fixes  #60
> Support methods in TypeScript declaration file

- packages/idx/package.json
Since there is no `tsconfig.json` we have to provide list of files to validate
> Fix tsc script in idx package 

- packages/idx/src/idx.d.ts
- packages/idx/src/idx.test.ts
* accept nullables as object argument so code like this works: 
```ts
let baz = idx(deep, _ => _.foo.bar.baz);
item = idx(baz, _ => _.arr[0].inner.item);
```
* simplify `FunctionWithRequiredReturnType` Thanks to @DanielRosenwasser [suggestion](https://twitter.com/drosenwasser/status/1066217309495283713) 
* use the built in type `NonNullable`
Fixes #64 
Fixes #63
> Allow nullables to be passed as a prop in TypeScript

- packages/idx/src/idx.d.ts
- packages/idx/src/idx.test.ts
```ts
type Obj = {
a?: {
b?: {
c?: number;
};
};
};
const result = idx({} as Obj, _ => _.a.b);
```
In that case `result` should be `{ c?: number }` instead of `DeepRequired<{ c?: number }>` ( as same as `{ c: number }`) .
So I introduce a new type `UnboxDeepRequired` and it works like this: 
`UnboxDeepRequired<DeepRequired<T>>` equals to `T`
> Add UnboxDeepRequired to fix return type

- packages/idx/src/idx.d.ts
- packages/idx/src/idx.test.ts
When end result is array or a function, return type of function or item type of the array should not be deeply required.
For instance 
```ts
type A = {
items?: (string | undefined)[]
}
idx({} as A, _ => _.items) // should return type (string | undefined)[] | undefined | null
```
> Fix UnboxDeepRequired type

- package.json
- packages/idx/package.json
- packages/idx/src/idx.d.ts
- packages/idx/src/idx.test.ts
Fixes #78 
* Make `DeepRequiredObject` strictly limited to `object` types so it doesn't unwrap primitive types 
* Update `UnboxDeepRequired` to check for objects and arrays before checking for primitives 
* Move TypeScript dependency down to idx package
> Fix types: support enums, make DeepRequiredObject limited to object

- packages/idx/src/idx.d.ts
In https://github.com/facebookincubator/idx/pull/80 `DeepRequiredObject` is limited to `object`. 
I think it is better to use `extends` in type param instead of type  expression.
Before:
```ts
type DeepRequiredObject<T> = T  extends object ? {
[P in keyof T]-?: DeepRequired<NonNullable<T[P]>>
} : T;
```
After:
```ts
type DeepRequiredObject<T extends object> = {
[P in keyof T]-?: DeepRequired<NonNullable<T[P]>>
};
```
---
I also refactor the `UnboxDeepRequired` otherwise unit test will fail:
```ts
type UnboxDeepRequired<T> = T extends DeepRequired<infer R> ? R : T;
```
We don't have to handle each case manually like
---
For details, these conditions may cause primitive type issue. For example is you pass `string` to `UnboxDeepRequired`:
```ts
type RequiredString = DeepRequired<string>; …
```
> Refactor DeepRequiredObject and support primitive

- packages/idx/src/idx.d.ts
- packages/idx/src/idx.test.ts
This PR is based on https://github.com/facebookincubator/idx/pull/84 . So please review / merge that PR before this.
Since `UnboxDeepRequired` is refactored to
```ts
type UnboxDeepRequired<T> = T extends DeepRequired<infer R> ? R : T;
```
It also support function return type. So I add a unit test case here.
@Jimexist
@mohsen1
@brieb
@yungsters
> Add test case for function return type

- packages/idx/src/idx.d.ts
(First of all, sorry the commit message is horrible...GitHub UI was a bit confusing there)
At the moment the types don't cover
```ts
interface B{
b: string
}
interface A{
getter() : B | undefined
}
const a = new A();
idx(A, _ => _.getter().B)
```
A workaround would be 
```ts
idx(A, _ => _.getter()!.B)
```
except this causes problems when used with https://github.com/dralletje/idx.macro because the `typescript` syntax makes it into the babel macro before it's transformed and thus you get a `buildCodeFrameError` with the message
> The `idx` body can only be composed of properties and methods.
I'm not a typing pro yet so especially for these recursive selectors I'm not sure if this would fix it but at least it's a "fixes-the-red-squiggly-lines" for me :-) Happy for input.
> WIP: Allow for undefined function return values.

- .husky/pre-commit
- package.json
- packages/idx/.flowconfig
- packages/idx/package.json
- packages/idx/src/idx.js.flow
- yarn.lock
In this PR, I switched the idx typing from a special cased flow builtin to a userland defined type powered by conditional and mapped type, similar to the TypeScript type definition provided.
Some notes on typing tricks:
- I used the trick of opaque type to better preserve the type application structure, so that they can be reliably unboxed in the `UnboxDeepRequired` type.
- I added the case for function types before `interface {}`, because function type is a subtype of `interface {}`...
Notes on the prettier change:
- We need to update to Prettier 3 to support the new flow syntax.
- `pretty-quick` doesn't work on Prettier 3, so I copied some bash script from prettier website instead.
> [flow] Update typing for idx
